# .github/workflows/pages.yml
name: Deploy static Next.js to GitHub Pages

on:
  push: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci

      # --- DEBUG: confirm envs are present (token not printed) ---
      - name: Debug env
        run: |
          node -e "console.log('GH_USER =', process.env.GH_USER); console.log('GH_TOKEN set =', Boolean(process.env.GH_TOKEN));"
        env:
          GH_USER: Tridude5
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # --- DEBUG: verify token identity (prints viewer login) ---
      - name: Who am I? (token viewer)
        run: |
          curl -s -H "Authorization: bearer $GH_TOKEN" -H "Content-Type: application/json" \
            -d '{"query":"query{viewer{login}}"}' https://api.github.com/graphql
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Run the fetcher explicitly (in addition to prebuild) so we can see its logs
      - name: Fetch GitHub contributions
        run: node scripts/fetch-contrib.mjs
        env:
          GH_USER: Tridude5
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # --- DEBUG: show generated JSON before build/export ---
      - name: Show contrib json (pre-build)
        run: |
          echo "public/github-contrib.json:"
          cat public/github-contrib.json || true
          echo "----"
          echo "Listing public/"
          ls -la public || true

      - name: Build (static export)
        run: npm run build            # runs prebuild -> fetch-contrib.mjs
        env:
          GH_USER: Tridude5           # must match the PAT owner
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # your PAT (classic) from repo secrets

      # --- DEBUG: confirm file made it into the export folder ---
      - name: Show exported files (post-build)
        run: |
          echo "Listing out/"
          ls -la out || true
          echo "out/github-contrib.json:"
          cat out/github-contrib.json || true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
